# Generated by Django 2.1.7 on 2019-03-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
