# Generated by Django 2.1.7 on 2019-03-23 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0002_ad_updated_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavouriteAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ads', to='ads.Ad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ad__created_on'],
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='users',
            field=models.ManyToManyField(related_name='ads_users', through='ads.UserFavouriteAds', to=settings.AUTH_USER_MODEL),
        ),
    ]
