# Generated by Django 2.1.7 on 2019-03-23 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0003_auto_20190323_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavouriteAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ad__created_on'],
            },
        ),
        migrations.RemoveField(
            model_name='userfavouriteads',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='userfavouriteads',
            name='user',
        ),
        migrations.AlterField(
            model_name='ad',
            name='users',
            field=models.ManyToManyField(related_name='user_ad', through='ads.UserFavouriteAd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserFavouriteAds',
        ),
        migrations.AddField(
            model_name='userfavouritead',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourite_ad', to='ads.Ad'),
        ),
        migrations.AddField(
            model_name='userfavouritead',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourite_ad', to=settings.AUTH_USER_MODEL),
        ),
    ]
